# Generated by Django 5.2 on 2026-01-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0005_alter_cartitem_variations"),
        ("store", "0011_alter_productgallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
