# Generated by Django 5.2 on 2026-01-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_variation_unique_product_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(upload_to="store/products"),
        ),
    ]
