# Generated by Django 5.2 on 2026-01-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_orderproduct_variations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
